### ISSUE TITLE
"Configure a GCP TCP Load Balancer" Question

### ISSUE THREAD

**Issue by dstroot** [fromAtoB/manifests#1]
Could you explain this just a bit better?

" Configure a GCP TCP Load Balancer and Health Check for all instances (/healthz) on the default-http-backend returns 200 OK - be sure to have a firewall setting so that the load balancer can reach the cluster on port 80 and 443"

I am also using GCloud and I understand the basics.  I just would appreciate a little more step by guidance please.  Vielen Dank!

**Comment by fortytw2** [comment]
Of course! Here are some screenshots of our TCP loadbalancer setup. The firewall rules need to allow port 80 and 443 to reach each of the kubernetes nodes from the load balancer (can provide an example of that, if needed). Hopefully this helps


To make a TCP loadbalancer go to `Networking -> Load Balancing`

<img width="1154" alt="screen shot 2017-03-19 at 5 12 11 pm" src="https://cloud.githubusercontent.com/assets/10286538/24082520/3e748452-0cc7-11e7-82c8-7ce5af9dff22.png">

Here's a backend configuration example for one

<img width="514" alt="screen shot 2017-03-19 at 5 10 13 pm" src="https://cloud.githubusercontent.com/assets/10286538/24082500/f853e08a-0cc6-11e7-92c2-bf99d3824862.png">

the frontend configuration looks something like 

<img width="500" alt="screen shot 2017-03-19 at 5 14 57 pm" src="https://cloud.githubusercontent.com/assets/10286538/24082533/a39f6aea-0cc7-11e7-89ba-552041c337da.png">


and the health check that goes along with it 

<img width="509" alt="screen shot 2017-03-19 at 5 10 49 pm" src="https://cloud.githubusercontent.com/assets/10286538/24082510/09a14d1e-0cc7-11e7-88bb-64521ec3da4a.png">

**Comment by dstroot** [comment]
Thank you so much!  I have it working now. 🥇
